export const TMDB_API_KEY =
	'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0YTZiMDIxZTE5Y2YxOTljMTM1NGFhMGRiMDZiOTkzMiIsInN1YiI6IjY0ODYzYWRmMDI4ZjE0MDExZTU1MDkwMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.yyMkZlhGOGBHtw1yvpBVUUHhu7IKVYho49MvNNKt_wY';
export const TMDB_IMAGES_ORIGINAL = 'https://www.themoviedb.org/t/p/original';
export const TMDB_BACKDROP_SMALL = 'https://www.themoviedb.org/t/p/w780';
export const TMDB_POSTER_SMALL = 'https://www.themoviedb.org/t/p/w342';
export const TMDB_PROFILE_SMALL = 'https://www.themoviedb.org/t/p/w185';

export const PLACEHOLDER_BACKDROP = '/placeholder.jpg';
export const LANGUAGES = [ // TODO: Load languages from Radarr and/or Sonarr API at startup
	"original",
	"afrikaans",
	"albanian",
	"arabic",
	"bengali",
	"bosnian",
	"bulgarian",
	"catalan",
	"chinese",
	"croatian",
	"czech",
	"danish",
	"dutch",
	"english",
	"estonian",
	"finnish",
	"flemish",
	"french",
	"georgian",
	"german",
	"greek",
	"hebrew",
	"hindi",
	"hungarian",
	"icelandic",
	"indonesian",
	"italian",
	"japanese",
	"kannada",
	"korean",
	"latvian",
	"lithuanian",
	"macedonian",
	"malayalam",
	"marathi",
	"mongolian",
	"norwegian",
	"persian",
	"polish",
	"portuguese",
	"portuguese (brazil)",
	"romanian",
	"romansh",
	"russian",
	"serbian",
	"slovak",
	"slovenian",
	"spanish",
	"spanish (latino)",
	"swedish",
	"tagalog",
	"tamil",
	"telugu",
	"thai",
	"turkish",
	"ukrainian",
	"urdu",
	"vietnamese"
]
export const QUALITY_DEFS = [
	"WORKPRINT",
	"CAM",
	"TELESYNC",
	"TELECINE",
	"REGIONAL",
	"DVDSCR",
	"SDTV",
	"DVD",
	"DVD-R",
	"WEBDL-480p",
	"WEBRip-480p",
	"Bluray-480p",
	"Bluray-576p",
	"HDTV-720p",
	"WEBDL-720p",
	"WEBRip-720p",
	"Bluray-720p",
	"HDTV-1080p",
	"WEBDL-1080p",
	"WEBRip-1080p",
	"Bluray-1080p",
	"Remux-1080p",
	"HDTV-2160p",
	"WEBDL-2160p",
	"WEBRip-2160p",
	"Bluray-2160p",
	"Remux-2160p",
	"BR-DISK",
	"Raw-HD"
]
